import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:intl/intl.dart';
import '../utils/colors.dart';
import 'package:ai_dietician/services2/spoonacular_services.dart';

class AIMeal {
  final String id;
  final String mealType;
  final String name;
  final String description;
  final double calories;
  final double protein;
  final double carbs;
  final double fat;
  final List<String> ingredients;
  final String preparationTime;
  final String difficulty;
  bool isActivated;
  final DateTime? activatedAt;
  final String? source;
  final String? sourceId;
  final String? imageUrl;
  final String? smartNote;
  final int? readyInMinutes;
  final int? servings;


  AIMeal({
    required this.id,
    required this.mealType,
    required this.name,
    required this.description,
    required this.calories,
    required this.protein,
    required this.carbs,
    required this.fat,
    required this.ingredients,
    required this.preparationTime,
    required this.difficulty,
    this.isActivated = false,
    this.activatedAt,
    this.source,
    this.sourceId,
    this.imageUrl,
    this.smartNote,
    this.readyInMinutes,
    this.servings,
  });


  Map<String, dynamic> toFirebaseMap() {
    return {
      'name': name,
      'calories': calories,
      'protein': protein,
      'carbs': carbs,
      'fat': fat,
      'mealType': mealType,
      'date': Timestamp.fromDate(DateTime.now()),
      'note': 'AI Generated by ${source ?? "Spoonacular"}: $description',
      'createdAt': Timestamp.now(),
      'isAIGenerated': true,
      'originalAIMealId': id,
      'source': source,
      'ingredients': ingredients,
      'preparationTime': preparationTime,
      'difficulty': difficulty,
      'imageUrl': imageUrl,
    };
  }
}

class DailyPlanScreen extends StatefulWidget {
  const DailyPlanScreen({Key? key}) : super(key: key);

  @override
  State<DailyPlanScreen> createState() => _DailyPlanScreenState();
}

class _DailyPlanScreenState extends State<DailyPlanScreen> {
  double _dailyCalorieGoal = 2000;
  List<Map<String, dynamic>> _todayMeals = [];
  double _totalCaloriesConsumed = 0;
  double _totalProtein = 0;
  double _totalCarbs = 0;
  double _totalFat = 0;
  bool _isLoading = true;


  List<AIMeal> _aiGeneratedMeals = [];
  bool _isGeneratingAI = false;
  bool _showAIMeals = false;
  String _userGoal = 'lose';
  String _dietaryPreferences = 'No restrictions';
  String _cuisinePreference = 'Any';
  int _mealsPerDay = 4;
  String _aiMessage = 'Ready to generate meals';
  bool _apiConnected = false;
  String _userDietType = 'balanced';
  List<String> _userAllergies = [];

  @override
  void initState() {
    super.initState();
    _loadUserData();
    _loadTodayMeals();
    _loadUserPreferences();
    _loadAIMeals();
    _testAPIConnection();
  }

  Future<void> _testAPIConnection() async {
    try {
      setState(() {
        _aiMessage = 'Testing Spoonacular API connection...';
      });

      await Future.delayed(Duration(seconds: 1));

      setState(() {
        _apiConnected = true;
        _aiMessage = 'Spoonacular API is ready!';
      });
    } catch (e) {
      print('API Test Error: $e');
      setState(() {
        _apiConnected = false;
        _aiMessage = '⚠️ API connection issue. Using smart algorithm.';
      });
    }
  }

  Future<void> _loadUserData() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      try {
        final doc = await FirebaseFirestore.instance
            .collection('users')
            .doc(user.uid)
            .get();

        if (doc.exists) {
          final data = doc.data()!;
          setState(() {
            _dailyCalorieGoal = (data['nutritionPlan']?['dailyCalories'] as num?)?.toDouble() ?? 2000;
          });
        }
      } catch (e) {
        print('Error loading user data: $e');
      }
    }
  }

  Future<void> _loadUserPreferences() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      try {
        final doc = await FirebaseFirestore.instance
            .collection('users')
            .doc(user.uid)
            .get();

        if (doc.exists) {
          final data = doc.data()!;
          setState(() {
            _userGoal = data['goal']?.toString() ?? 'lose';

            _userDietType = data['dietType']?.toString() ?? 'balanced';

            _userAllergies = List<String>.from(data['dietaryRestrictions'] ?? []);

            _cuisinePreference = data['cuisinePreference']?.toString() ?? 'Any';
            _mealsPerDay = (data['mealsPerDay'] as int?) ?? 4;
          });
        }
      } catch (e) {
        print('Error loading user preferences: $e');
      }
    }
  }

  Future<void> _loadTodayMeals() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      try {
        final today = DateTime.now();
        final startOfDay = DateTime(today.year, today.month, today.day);
        final endOfDay = DateTime(today.year, today.month, today.day, 23, 59, 59);

        final snapshot = await FirebaseFirestore.instance
            .collection('users')
            .doc(user.uid)
            .collection('daily_logs')
            .where('date', isGreaterThanOrEqualTo: Timestamp.fromDate(startOfDay))
            .where('date', isLessThanOrEqualTo: Timestamp.fromDate(endOfDay))
            .orderBy('date', descending: true)
            .get();

        if (snapshot.docs.isNotEmpty) {
          final List<Map<String, dynamic>> meals = [];
          double totalCalories = 0;
          double totalProtein = 0;
          double totalCarbs = 0;
          double totalFat = 0;

          for (var doc in snapshot.docs) {
            final data = doc.data();
            meals.add({
              'id': doc.id,
              'name': data['name'] ?? 'Meal',
              'calories': (data['calories'] as num?)?.toDouble() ?? 0,
              'protein': (data['protein'] as num?)?.toDouble() ?? 0,
              'carbs': (data['carbs'] as num?)?.toDouble() ?? 0,
              'fat': (data['fat'] as num?)?.toDouble() ?? 0,
              'mealType': data['mealType'] ?? 'Lunch',
              'time': (data['date'] as Timestamp).toDate(),
              'note': data['note'] ?? '',
              'isAIGenerated': data['isAIGenerated'] ?? false,
            });

            totalCalories += (data['calories'] as num?)?.toDouble() ?? 0;
            totalProtein += (data['protein'] as num?)?.toDouble() ?? 0;
            totalCarbs += (data['carbs'] as num?)?.toDouble() ?? 0;
            totalFat += (data['fat'] as num?)?.toDouble() ?? 0;
          }

          setState(() {
            _todayMeals = meals;
            _totalCaloriesConsumed = totalCalories;
            _totalProtein = totalProtein;
            _totalCarbs = totalCarbs;
            _totalFat = totalFat;
          });
        } else {
          setState(() {
            _todayMeals = [];
            _totalCaloriesConsumed = 0;
            _totalProtein = 0;
            _totalCarbs = 0;
            _totalFat = 0;
          });
        }
      } catch (e) {
        print('Error loading meals: $e');
      } finally {
        setState(() {
          _isLoading = false;
        });
      }
    }
  }

  Future<void> _loadAIMeals() async {
    setState(() {
      _isGeneratingAI = true;
    });

    try {
      final today = DateTime.now();
      final dateStr = DateFormat('yyyy-MM-dd').format(today);

      final doc = await FirebaseFirestore.instance
          .collection('users')
          .doc(FirebaseAuth.instance.currentUser!.uid)
          .collection('ai_generated_meals')
          .doc(dateStr)
          .get();

      if (doc.exists && doc.data() != null) {
        final data = doc.data()!;
        final meals = data['meals'] as List<dynamic>;

        final aiMeals = meals.asMap().entries.map((entry) {
          final mealData = entry.value as Map<String, dynamic>;
          return AIMeal(
            id: '${mealData['id'] ?? 'ai_${entry.key}'}',
            mealType: mealData['mealType'] ?? 'Lunch',
            name: mealData['name'] ?? 'AI Meal',
            description: mealData['description'] ?? '',
            calories: (mealData['calories'] as num?)?.toDouble() ?? 0,
            protein: (mealData['protein'] as num?)?.toDouble() ?? 0,
            carbs: (mealData['carbs'] as num?)?.toDouble() ?? 0,
            fat: (mealData['fat'] as num?)?.toDouble() ?? 0,
            ingredients: List<String>.from(mealData['ingredients'] ?? []),
            preparationTime: mealData['preparationTime'] ?? '20-30 minutes',
            difficulty: mealData['difficulty'] ?? 'Medium',
            source: mealData['source'] ?? 'Spoonacular',
            sourceId: mealData['sourceId']?.toString(),
            imageUrl: mealData['imageUrl']?.toString(),
            smartNote: mealData['smartNote']?.toString(),
            readyInMinutes: (mealData['readyInMinutes'] as num?)?.toInt(),
            servings: (mealData['servings'] as num?)?.toInt(),
          );
        }).toList();

        setState(() {
          _aiGeneratedMeals = aiMeals;
          _showAIMeals = true;
        });
      }
    } catch (e) {
      print('Error loading AI meals: $e');
    } finally {
      setState(() {
        _isGeneratingAI = false;
      });
    }
  }

  Future<void> _saveMealToFirebase(Map<String, dynamic> mealData) async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      try {
        await FirebaseFirestore.instance
            .collection('users')
            .doc(user.uid)
            .collection('daily_logs')
            .add(mealData);

        await _updateDailyStats();
        await _loadTodayMeals();

        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(' Meal added successfully'),
            backgroundColor: Colors.green,
            duration: Duration(seconds: 2),
          ),
        );
      } catch (e) {
        print('Error saving meal: $e');
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(' Error saving meal'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  Future<void> _updateDailyStats() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      try {
        final today = DateTime.now();
        final startOfDay = DateTime(today.year, today.month, today.day);
        final dateStr = DateFormat('yyyy-MM-dd').format(today);

        await FirebaseFirestore.instance
            .collection('users')
            .doc(user.uid)
            .collection('daily_stats')
            .doc(dateStr)
            .set({
          'date': Timestamp.fromDate(startOfDay),
          'totalCalories': _totalCaloriesConsumed,
          'totalProtein': _totalProtein,
          'totalCarbs': _totalCarbs,
          'totalFat': _totalFat,
          'mealCount': _todayMeals.length,
          'updatedAt': Timestamp.now(),
        }, SetOptions(merge: true));
      } catch (e) {
        print('Error updating daily stats: $e');
      }
    }
  }

  Future<void> _deleteMeal(String mealId) async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      try {
        await FirebaseFirestore.instance
            .collection('users')
            .doc(user.uid)
            .collection('daily_logs')
            .doc(mealId)
            .delete();

        await _loadTodayMeals();

        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Meal deleted'),
            backgroundColor: Colors.red,
          ),
        );
      } catch (e) {
        print('Error deleting meal: $e');
      }
    }
  }

  Future<void> _generateAIMealPlan() async {
    setState(() {
      _isGeneratingAI = true;
      _aiMessage = '🤖 Connecting to Spoonacular AI...';
    });

    try {
      final List<Map<String, dynamic>> mealsData = await SpoonacularService.generateDailyMealPlan(
        dailyCalories: _dailyCalorieGoal,
        goal: _userGoal,
        dietType: _userDietType,
        dietaryRestrictions: _userAllergies,
        mealsPerDay: _mealsPerDay,
        cuisinePreference: _cuisinePreference,
      );

      final List<AIMeal> aiMeals = mealsData.map((meal) {
        return AIMeal(
          id: meal['id']?.toString() ?? DateTime.now().millisecondsSinceEpoch.toString(),
          mealType: meal['mealType'] ?? 'Meal',
          name: meal['name'] ?? 'Unknown Meal',
          description: meal['description'] ?? '',
          calories: (meal['calories'] as num?)?.toDouble() ?? 0.0,
          protein: (meal['protein'] as num?)?.toDouble() ?? 0.0,
          carbs: (meal['carbs'] as num?)?.toDouble() ?? 0.0,
          fat: (meal['fat'] as num?)?.toDouble() ?? 0.0,
          ingredients: List<String>.from(meal['ingredients'] ?? []),
          preparationTime: meal['preparationTime'] ?? '20 mins',
          difficulty: meal['difficulty'] ?? 'Medium',
          imageUrl: meal['imageUrl'],
          source: 'Spoonacular',
        );
      }).toList();

      setState(() {
        _aiGeneratedMeals = aiMeals;
        _showAIMeals = true;
        _apiConnected = true;
        _aiMessage = '✅ AI Plan Generated Successfully!';
      });

      await SpoonacularService.saveGeneratedMealsToFirebase(mealsData);

    } catch (e) {
      print('❌ Detailed Error during parsing: $e');
      setState(() {
        _aiMessage = 'Connection issue. Using smart backup.';
        _apiConnected = false;
      });
      await _generateSmartMealPlan();
    } finally {
      setState(() { _isGeneratingAI = false; });
    }
  }

  Future<void> _generateSmartMealPlan() async {
    setState(() {
      _aiMessage = '🧠 Generating smart meals...';
    });

    await Future.delayed(Duration(seconds: 2));

    final aiMeals = List.generate(_mealsPerDay, (index) {
      final mealTypes = ['Breakfast', 'Lunch', 'Dinner', 'Snack'];
      final mealType = index < mealTypes.length ? mealTypes[index] : 'Meal ${index + 1}';
      final caloriesPerMeal = _dailyCalorieGoal / _mealsPerDay;

      return AIMeal(
        id: 'smart_$index',
        mealType: mealType,
        name: 'Smart $mealType',
        description: 'AI-generated meal optimized for your $mealType goal',
        calories: caloriesPerMeal,
        protein: _calculateProteinForGoal(_userGoal, mealType),
        carbs: _calculateCarbsForGoal(_userGoal, mealType),
        fat: _calculateFatForGoal(_userGoal, mealType),
        ingredients: ['Fresh vegetables', 'Lean protein', 'Whole grains', 'Healthy fats'],
        preparationTime: '15-25 minutes',
        difficulty: 'Easy',
        source: 'Smart Algorithm',
        smartNote: _generateSmartNote(_userGoal, mealType),
      );
    });

    setState(() {
      _aiGeneratedMeals = aiMeals;
      _showAIMeals = true;
      _aiMessage = ' Smart meals generated!';
    });
  }

  double _calculateProteinForGoal(String goal, String mealType) {
    double baseProtein = 25.0;

    if (goal == 'lose') baseProtein *= 1.2;
    if (goal == 'gain') baseProtein *= 1.3;

    if (mealType == 'Breakfast') return baseProtein * 0.8;
    if (mealType == 'Lunch') return baseProtein * 1.1;
    if (mealType == 'Dinner') return baseProtein * 1.0;
    return baseProtein * 0.6;
  }

  double _calculateCarbsForGoal(String goal, String mealType) {
    double baseCarbs = 40.0;

    if (goal == 'lose') baseCarbs *= 0.8;
    if (goal == 'gain') baseCarbs *= 1.4;

    if (mealType == 'Breakfast') return baseCarbs * 1.1;
    if (mealType == 'Lunch') return baseCarbs * 1.0;
    if (mealType == 'Dinner') return baseCarbs * 0.7;
    return baseCarbs * 0.5;
  }

  double _calculateFatForGoal(String goal, String mealType) {
    double baseFat = 12.0;

    if (goal == 'lose') baseFat *= 0.8;
    if (goal == 'gain') baseFat *= 1.2;

    if (mealType == 'Breakfast') return baseFat * 0.9;
    if (mealType == 'Lunch') return baseFat * 1.0;
    if (mealType == 'Dinner') return baseFat * 1.1;
    return baseFat * 0.7;
  }

  String _generateSmartNote(String goal, String mealType) {
    Map<String, Map<String, String>> notes = {
      'lose': {
        'Breakfast': 'High protein breakfast to control hunger',
        'Lunch': 'Balanced meal for sustained energy',
        'Dinner': 'Light dinner to promote fat burning',
        'Snack': 'Low-calorie snack to curb cravings',
      },
      'gain': {
        'Breakfast': 'Calorie-dense breakfast for muscle growth',
        'Lunch': 'Protein and carb-rich meal for energy',
        'Dinner': 'Nutrient-packed dinner for recovery',
        'Snack': 'Protein-rich snack for muscle maintenance',
      },
      'maintain': {
        'Breakfast': 'Perfectly balanced breakfast',
        'Lunch': 'Nutritious lunch for optimal performance',
        'Dinner': 'Healthy dinner for wellbeing',
        'Snack': 'Smart snack for stable blood sugar',
      },
    };

    return notes[goal]?[mealType] ?? 'Healthy and balanced meal';
  }

  Future<void> _activateAIMeal(AIMeal aiMeal) async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      try {
        await _saveMealToFirebase(aiMeal.toFirebaseMap());

        setState(() {
          _aiGeneratedMeals = _aiGeneratedMeals.map((meal) {
            if (meal.id == aiMeal.id) {
              return AIMeal(
                id: meal.id,
                mealType: meal.mealType,
                name: meal.name,
                description: meal.description,
                calories: meal.calories,
                protein: meal.protein,
                carbs: meal.carbs,
                fat: meal.fat,
                ingredients: meal.ingredients,
                preparationTime: meal.preparationTime,
                difficulty: meal.difficulty,
                isActivated: true,
                activatedAt: DateTime.now(),
                source: meal.source,
                sourceId: meal.sourceId,
                imageUrl: meal.imageUrl,
                smartNote: meal.smartNote,
                readyInMinutes: meal.readyInMinutes,
                servings: meal.servings,
              );
            }
            return meal;
          }).toList();
        });

        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('✅ ${aiMeal.name} added to your daily log!'),
            backgroundColor: Colors.green,
          ),
        );
      } catch (e) {
        print('Error activating AI meal: $e');
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('❌ Error adding meal. Please try again.'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  void _showAddMealDialog(String mealType) {
    TextEditingController nameController = TextEditingController();
    TextEditingController caloriesController = TextEditingController();
    TextEditingController proteinController = TextEditingController();
    TextEditingController carbsController = TextEditingController();
    TextEditingController fatController = TextEditingController();
    TextEditingController noteController = TextEditingController();

    showDialog(
      context: context,
      builder: (context) => StatefulBuilder(
        builder: (context, setState) {
          return AlertDialog(
            title: Row(
              children: [
                Icon(Icons.restaurant, color: AppColors.lightPurple),
                SizedBox(width: 8),
                Text('Add $mealType'),
              ],
            ),
            content: SingleChildScrollView(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  TextField(
                    controller: nameController,
                    decoration: InputDecoration(
                      labelText: 'Meal Name',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.fastfood),
                    ),
                  ),
                  SizedBox(height: 12),
                  Row(
                    children: [
                      Expanded(
                        child: TextField(
                          controller: caloriesController,
                          keyboardType: TextInputType.number,
                          decoration: InputDecoration(
                            labelText: 'Calories',
                            border: OutlineInputBorder(),
                            prefixIcon: Icon(Icons.local_fire_department),
                          ),
                        ),
                      ),
                      SizedBox(width: 12),
                      Expanded(
                        child: TextField(
                          controller: proteinController,
                          keyboardType: TextInputType.number,
                          decoration: InputDecoration(
                            labelText: 'Protein (g)',
                            border: OutlineInputBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                  SizedBox(height: 12),
                  Row(
                    children: [
                      Expanded(
                        child: TextField(
                          controller: carbsController,
                          keyboardType: TextInputType.number,
                          decoration: InputDecoration(
                            labelText: 'Carbs (g)',
                            border: OutlineInputBorder(),
                          ),
                        ),
                      ),
                      SizedBox(width: 12),
                      Expanded(
                        child: TextField(
                          controller: fatController,
                          keyboardType: TextInputType.number,
                          decoration: InputDecoration(
                            labelText: 'Fat (g)',
                            border: OutlineInputBorder(),
                          ),
                        ),
                      ),
                    ],
                  ),
                  SizedBox(height: 12),
                  TextField(
                    controller: noteController,
                    maxLines: 3,
                    decoration: InputDecoration(
                      labelText: 'Notes (optional)',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.note),
                    ),
                  ),
                ],
              ),
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(context),
                child: Text('Cancel'),
              ),
              ElevatedButton(
                onPressed: () async {
                  final calories = double.tryParse(caloriesController.text) ?? 0;
                  final protein = double.tryParse(proteinController.text) ?? 0;
                  final carbs = double.tryParse(carbsController.text) ?? 0;
                  final fat = double.tryParse(fatController.text) ?? 0;

                  if (nameController.text.isNotEmpty && calories > 0) {
                    final mealData = {
                      'name': nameController.text,
                      'calories': calories,
                      'protein': protein,
                      'carbs': carbs,
                      'fat': fat,
                      'mealType': mealType,
                      'date': Timestamp.now(),
                      'note': noteController.text,
                      'createdAt': Timestamp.now(),
                      'isAIGenerated': false,
                    };

                    Navigator.pop(context);
                    await _saveMealToFirebase(mealData);
                  }
                },
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.lightPurple,
                  foregroundColor: Colors.white,
                ),
                child: Text('Add Meal'),
              ),
            ],
          );
        },
      ),
    );
  }

  Future<void> _completeDay() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      try {
        final currentStreak = await _getCurrentStreak();
        await FirebaseFirestore.instance
            .collection('users')
            .doc(user.uid)
            .update({
          'streak': currentStreak + 1,
          'lastCompletedDay': Timestamp.now(),
        });

        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('🎉 Day completed! Streak updated to ${currentStreak + 1} days'),
            backgroundColor: Colors.green,
            duration: Duration(seconds: 3),
          ),
        );
      } catch (e) {
        print('Error completing day: $e');
      }
    }
  }

  Future<int> _getCurrentStreak() async {
    final user = FirebaseAuth.instance.currentUser;
    if (user != null) {
      final doc = await FirebaseFirestore.instance
          .collection('users')
          .doc(user.uid)
          .get();

      if (doc.exists) {
        return (doc.data()?['streak'] as int?) ?? 0;
      }
    }
    return 0;
  }

  Widget _buildCalorieSummary() {
    final remainingCalories = _dailyCalorieGoal - _totalCaloriesConsumed;

    return Card(
      margin: EdgeInsets.all(16),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
      ),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          children: [
            Text(
              'Daily Calories',
              style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 16),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceAround,
              children: [
                _buildCalorieBox('Goal', _dailyCalorieGoal.round()),
                _buildCalorieBox('Consumed', _totalCaloriesConsumed.round()),
                _buildCalorieBox(
                  'Remaining',
                  remainingCalories.round(),
                  color: remainingCalories > 0 ? Colors.green : Colors.red,
                ),
              ],
            ),
            SizedBox(height: 16),
            LinearProgressIndicator(
              value: (_totalCaloriesConsumed / _dailyCalorieGoal).clamp(0.0, 1.0),
              backgroundColor: Colors.grey[200],
              color: AppColors.lightPurple,
              minHeight: 10,
              borderRadius: BorderRadius.circular(5),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildCalorieBox(String label, int value, {Color? color}) {
    return Column(
      children: [
        Text(label, style: TextStyle(fontSize: 12, color: Colors.grey[600])),
        SizedBox(height: 4),
        Text('$value', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: color ?? Colors.black)),
        Text('cal', style: TextStyle(fontSize: 10, color: Colors.grey)),
      ],
    );
  }

  Widget _buildMacroSummary() {
    return Card(
      margin: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
      ),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text("Today's Macros", style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
            SizedBox(height: 12),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                _buildMacroSummaryItem('Protein', '${_totalProtein.round()}g', Colors.blue),
                _buildMacroSummaryItem('Carbs', '${_totalCarbs.round()}g', Colors.green),
                _buildMacroSummaryItem('Fat', '${_totalFat.round()}g', Colors.orange),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildMacroSummaryItem(String label, String value, Color color) {
    return Column(
      children: [
        Container(
          width: 60,
          height: 60,
          decoration: BoxDecoration(
            color: color.withOpacity(0.1),
            borderRadius: BorderRadius.circular(30),
            border: Border.all(color: color.withOpacity(0.3), width: 2),
          ),
          child: Center(
            child: Text(
              value,
              style: TextStyle(fontSize: 14, fontWeight: FontWeight.bold, color: color),
            ),
          ),
        ),
        SizedBox(height: 8),
        Text(label, style: TextStyle(fontSize: 12, color: Colors.grey[600])),
      ],
    );
  }

  Widget _buildAISection() {
    final screenWidth = MediaQuery.of(context).size.width;

    return Card(
      margin: EdgeInsets.symmetric(horizontal: screenWidth * 0.04, vertical: 8),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
      ),
      child: Padding(
        padding: EdgeInsets.all(screenWidth * 0.04),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Header Row
            Wrap( // استخدام Wrap بدلاً من Row لمنع الـ Overflow عند ظهور الزر
              alignment: WrapAlignment.spaceBetween,
              crossAxisAlignment: WrapCrossAlignment.center,
              spacing: 10,
              runSpacing: 10,
              children: [
                Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    const Icon(Icons.auto_awesome, color: Colors.purple),
                    const SizedBox(width: 8),
                    Text(
                        'AI Meal Suggestions',
                        style: TextStyle(
                            fontSize: screenWidth * 0.045,
                            fontWeight: FontWeight.bold
                        )
                    ),
                  ],
                ),
                if (!_showAIMeals || _aiGeneratedMeals.isEmpty)
                  _buildSmallGenerateButton(screenWidth),
              ],
            ),

            const SizedBox(height: 12),

            // API Status Indicator
            Container(
              padding: const EdgeInsets.all(10),
              decoration: BoxDecoration(
                color: _apiConnected ? Colors.green[50] : Colors.orange[50],
                borderRadius: BorderRadius.circular(10),
                border: Border.all(
                    color: _apiConnected ? Colors.green.withOpacity(0.2) : Colors.orange.withOpacity(0.2)
                ),
              ),
              child: Row(
                children: [
                  Icon(
                    _apiConnected ? Icons.check_circle : Icons.info,
                    color: _apiConnected ? Colors.green : Colors.orange,
                    size: 16,
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      _aiMessage,
                      style: TextStyle(
                        fontSize: screenWidth * 0.03,
                        color: _apiConnected ? Colors.green[800] : Colors.orange[800],
                      ),
                    ),
                  ),
                ],
              ),
            ),

            const SizedBox(height: 16),

            // Main Content Area
            _buildAIContent(screenWidth),
          ],
        ),
      ),
    );
  }

// دالة مساعدة لتنظيم المحتوى الداخلي للـ AI
  Widget _buildAIContent(double screenWidth) {
    if (_isGeneratingAI) {
      return Center(
        child: Column(
          children: [
            const CircularProgressIndicator(color: Colors.purple),
            const SizedBox(height: 12),
            Text(
              'AI is creating your personalized plan...',
              textAlign: TextAlign.center,
              style: TextStyle(fontSize: screenWidth * 0.035),
            ),
            const SizedBox(height: 4),
            Text(
                'This may take a few seconds',
                style: TextStyle(fontSize: screenWidth * 0.03, color: Colors.grey)
            ),
          ],
        ),
      );
    } else if (_showAIMeals && _aiGeneratedMeals.isNotEmpty) {
      return Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
              'Your AI-generated meal plan for today:',
              style: TextStyle(color: Colors.grey[600], fontSize: screenWidth * 0.035)
          ),
          const SizedBox(height: 12),
          // عرض الوجبات
          ..._aiGeneratedMeals.map((aiMeal) => _buildAIMealCard(aiMeal)).toList(),
        ],
      );
    } else {
      // الحالة الافتراضية قبل التوليد
      return Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
              'Let AI create a personalized meal plan for you!',
              style: TextStyle(color: Colors.grey[600], fontSize: screenWidth * 0.035)
          ),
          const SizedBox(height: 10),
          _buildInstructionRow(Icons.bolt, 'Based on your calorie goal', screenWidth),
          _buildInstructionRow(Icons.restaurant, '500,000+ recipes available', screenWidth),
          _buildInstructionRow(Icons.touch_app, 'Click to get started', screenWidth),
          const SizedBox(height: 16),
          ElevatedButton(
            onPressed: _generateAIMealPlan,
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.purple,
              foregroundColor: Colors.white,
              minimumSize: const Size(double.infinity, 50),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            ),
            child: Text('Generate AI Meal Plan', style: TextStyle(fontSize: screenWidth * 0.04)),
          ),
        ],
      );
    }
  }

// دالة مساعدة للزر الصغير في الأعلى
  Widget _buildSmallGenerateButton(double screenWidth) {
    return ElevatedButton.icon(
      onPressed: _isGeneratingAI ? null : _generateAIMealPlan,
      style: ElevatedButton.styleFrom(
        backgroundColor: Colors.purple,
        foregroundColor: Colors.white,
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
      ),
      icon: _isGeneratingAI
          ? SizedBox(width: 14, height: 14, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white.withOpacity(0.5)))
          : const Icon(Icons.auto_awesome, size: 14),
      label: Text(
          _isGeneratingAI ? '...' : 'Generate',
          style: TextStyle(fontSize: screenWidth * 0.03)
      ),
    );
  }

// دالة مساعدة لتنسيق أسطر التعليمات
  Widget _buildInstructionRow(IconData icon, String text, double screenWidth) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 6),
      child: Row(
        children: [
          Icon(icon, size: 14, color: Colors.purple.withOpacity(0.7)),
          const SizedBox(width: 8),
          Text(text, style: TextStyle(fontSize: screenWidth * 0.032, color: Colors.black87)),
        ],
      ),
    );
  }

  Widget _buildAIMealCard(AIMeal aiMeal) {
    return Card(
        margin: EdgeInsets.only(bottom: 12),
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
          side: BorderSide(
            color: aiMeal.isActivated ? Colors.green : Colors.grey[300]!,
            width: 1,
          ),
        ),
        child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
        if (aiMeal.imageUrl != null && aiMeal.imageUrl!.isNotEmpty)
        ClipRRect(
    borderRadius: BorderRadius.only(
    topLeft: Radius.circular(12),
    topRight: Radius.circular(12),
    ),
    child: Image.network(
    aiMeal.imageUrl!,
    height: 120,
    width: double.infinity,
    fit: BoxFit.cover,
    loadingBuilder: (context, child, loadingProgress) {
    if (loadingProgress == null) return child;
    return Container(
    height: 120,
    color: Colors.grey[200],
    child: Center(
    child: CircularProgressIndicator(
    value: loadingProgress.expectedTotalBytes != null
    ? loadingProgress.cumulativeBytesLoaded / loadingProgress.expectedTotalBytes! : null,
    ),
    ),
    );
    },
      errorBuilder: (context, error, stackTrace) {
      return Container(
        height: 120,
        color: Colors.grey[200],
        child: Center(
          child: Icon(Icons.restaurant, size: 40, color: Colors.grey[400]),
        ),
      );
    },
    ),
        ),

              Padding(
                padding: const EdgeInsets.all(12),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [

                    Row(
                      children: [
                        Expanded(
                          flex: 3,
                          child: Row(
                            children: [
                              Container(
                                padding: EdgeInsets.all(6),
                                decoration: BoxDecoration(
                                  color: _getMealTypeColor(aiMeal.mealType).withOpacity(0.2),
                                  borderRadius: BorderRadius.circular(8),
                                ),
                                child: Icon(
                                  _getMealIcon(aiMeal.mealType),
                                  color: _getMealTypeColor(aiMeal.mealType),
                                  size: 18,
                                ),
                              ),
                              SizedBox(width: 8),
                              Expanded(
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    Text(
                                      aiMeal.name,
                                      style: TextStyle(fontWeight: FontWeight.bold),
                                      overflow: TextOverflow.ellipsis,
                                      maxLines: 1,
                                    ),
                                    SizedBox(height: 2),
                                    Text(
                                      aiMeal.mealType,
                                      style: TextStyle(fontSize: 10, color: Colors.grey),
                                      overflow: TextOverflow.ellipsis,
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                        if (aiMeal.isActivated)
                          Chip(
                            label: Text('Added', style: TextStyle(fontSize: 10)),
                            backgroundColor: Colors.green.withOpacity(0.2),
                            labelStyle: TextStyle(color: Colors.green),
                            padding: EdgeInsets.symmetric(horizontal: 4),
                          )
                        else
                          ElevatedButton(
                            onPressed: () => _activateAIMeal(aiMeal),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: Colors.purple,
                              foregroundColor: Colors.white,
                              padding: EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                              minimumSize: Size(0, 30),
                              tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                            ),
                            child: Text('Add', style: TextStyle(fontSize: 12)),
                          ),
                      ],
                    ),

                    SizedBox(height: 10),
                    Text(aiMeal.description, style: TextStyle(fontSize: 13, color: Colors.grey[700])),

                    if (aiMeal.smartNote != null)
                      Padding(
                        padding: const EdgeInsets.only(top: 8.0),
                        child: Text(
                          aiMeal.smartNote!,
                          style: TextStyle(fontSize: 12, color: Colors.blue[700], fontStyle: FontStyle.italic),
                        ),
                      ),

                    SizedBox(height: 12),
                    Wrap(
                      spacing: 6,
                      runSpacing: 6,
                      children: [
                        _buildNutritionBadge('🔥', '${aiMeal.calories.round()} cal', Colors.orange),
                        _buildNutritionBadge('💪', '${aiMeal.protein.round()}g P', Colors.blue),
                        _buildNutritionBadge('🌾', '${aiMeal.carbs.round()}g C', Colors.green),
                        _buildNutritionBadge('🥑', '${aiMeal.fat.round()}g F', Colors.orange),
                      ],
                    ),

                    SizedBox(height: 10),
                    Wrap(
                      spacing: 6,
                      runSpacing: 6,
                      children: [
                        Chip(
                          label: Text(aiMeal.preparationTime, style: TextStyle(fontSize: 10)),
                          backgroundColor: Colors.blue.withOpacity(0.1),
                          labelStyle: TextStyle(color: Colors.blue),
                        ),
                        Chip(
                          label: Text(aiMeal.difficulty, style: TextStyle(fontSize: 10)),
                          backgroundColor: Colors.green.withOpacity(0.1),
                          labelStyle: TextStyle(color: Colors.green),
                        ),
                        if (aiMeal.source != null)
                          Chip(
                            label: Text(aiMeal.source!, style: TextStyle(fontSize: 10)),
                            backgroundColor: Colors.purple.withOpacity(0.1),
                            labelStyle: TextStyle(color: Colors.purple),
                          ),
                      ],
                    ),

                    SizedBox(height: 8),
                    Text('Ingredients:', style: TextStyle(fontSize: 12, fontWeight: FontWeight.w500)),
                    SizedBox(height: 4),
                    Wrap(
                      spacing: 6,
                      runSpacing: 4,
                      children: aiMeal.ingredients.take(4).map((ingredient) => Chip(
                        label: Text(ingredient, style: TextStyle(fontSize: 10)),
                        backgroundColor: Colors.grey[100],
                      )).toList(),
                    ),
                  ],
                ),
              ),
            ],
        ),
    );
  }

  Widget _buildNutritionBadge(String icon, String text, Color color) {
    return Container(
      padding: EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: color.withOpacity(0.3)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(icon, style: TextStyle(fontSize: 10)),
          SizedBox(width: 4),
          Flexible(
            child: Text(
              text,
              style: TextStyle(fontSize: 10, fontWeight: FontWeight.w600, color: color),
              maxLines: 1,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildMealSection(String title, String mealType, IconData icon) {
    final meals = _todayMeals.where((meal) => meal['mealType'].toString().toLowerCase() == mealType.toLowerCase()).toList();
    final total = meals.fold(0.0, (sum, meal) => sum + (meal['calories'] as double));

    return Card(
      margin: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(16),
      ),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Row(
                  children: [
                    Icon(icon, color: AppColors.lightPurple),
                    SizedBox(width: 8),
                    Text(title, style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                  ],
                ),
                Text('${total.round()} cal', style: TextStyle(color: AppColors.lightPurple, fontWeight: FontWeight.w600)),
              ],
            ),
            SizedBox(height: 12),

            if (_isLoading)
              Center(child: CircularProgressIndicator(color: AppColors.lightPurple))
            else if (meals.isEmpty)
              Center(child: Text('No meals added yet', style: TextStyle(color: Colors.grey)))
            else
              ...meals.map((meal) => ListTile(
                contentPadding: EdgeInsets.symmetric(vertical: 4),
                leading: Icon(_getMealIcon(meal['mealType'].toString()), color: AppColors.lightPurple),
                title: Text(meal['name'].toString(), style: TextStyle(fontWeight: FontWeight.w500)),
                subtitle: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    SizedBox(height: 4),
                    Text('${(meal['calories'] as double).round()} calories'),
                    SizedBox(height: 4),
                    Wrap(
                      spacing: 6,
                      children: [
                        _buildMacroChip('P', '${(meal['protein'] as double).round()}g', Colors.blue),
                        _buildMacroChip('C', '${(meal['carbs'] as double).round()}g', Colors.green),
                        _buildMacroChip('F', '${(meal['fat'] as double).round()}g', Colors.orange),
                      ],
                    ),
                    if (meal['isAIGenerated'] == true)
                      Container(
                        margin: EdgeInsets.only(top: 4),
                        padding: EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                        decoration: BoxDecoration(
                          color: Colors.purple.withOpacity(0.1),
                          borderRadius: BorderRadius.circular(4),
                        ),
                        child: Text(
                          'AI Generated',
                          style: TextStyle(fontSize: 10, color: Colors.purple),
                        ),
                      ),
                    if (meal['note'].toString().isNotEmpty)
                      Padding(
                        padding: const EdgeInsets.only(top: 4.0),
                        child: Text(
                          meal['note'].toString(),
                          style: TextStyle(fontSize: 11, color: Colors.grey[600], fontStyle: FontStyle.italic),
                          maxLines: 1,
                          overflow: TextOverflow.ellipsis,
                        ),
                      ),
                  ],
                ),
                trailing: IconButton(
                  icon: Icon(Icons.delete_outline, size: 20, color: Colors.red),
                  onPressed: () => _deleteMeal(meal['id'].toString()),
                ),
              )).toList(),

            SizedBox(height: 12),
            ElevatedButton(
              onPressed: () => _showAddMealDialog(mealType),
              style: ElevatedButton.styleFrom(
                backgroundColor: AppColors.lightPurple,
                foregroundColor: Colors.white,
                minimumSize: Size(double.infinity, 50),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(12),
                ),
              ),
              child: Text('Add $title'),
            ),
          ],
        ),
      ),
    );
  }

  IconData _getMealIcon(String mealType) {
    switch (mealType.toLowerCase()) {
      case 'breakfast': return Icons.breakfast_dining;
      case 'lunch': return Icons.lunch_dining;
      case 'dinner': return Icons.dinner_dining;
      case 'snack': return Icons.local_cafe;
      default: return Icons.restaurant;
    }
  }

  Color _getMealTypeColor(String mealType) {
    switch (mealType.toLowerCase()) {
      case 'breakfast': return Colors.orange;
      case 'lunch': return Colors.green;
      case 'dinner': return Colors.blue;
      case 'snack': return Colors.purple;
      default: return Colors.grey;
    }
  }

  Widget _buildMacroChip(String label, String value, Color color) {
    return Container(
      padding: EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: color.withOpacity(0.3)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            '$label: ',
            style: TextStyle(fontSize: 10, color: color),
          ),
          Text(
            value,
            style: TextStyle(fontSize: 10, fontWeight: FontWeight.bold, color: color),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Daily Plan'),
        centerTitle: true,
        backgroundColor: Colors.white,
        elevation: 0,
        actions: [
          IconButton(
            icon: Icon(Icons.auto_awesome, color: _showAIMeals ? Colors.purple : Colors.grey),
            onPressed: () {
              setState(() {
                _showAIMeals = !_showAIMeals;
              });
            },
            tooltip: 'Toggle AI Suggestions',
          ),
          IconButton(
            icon: Icon(Icons.refresh, color: AppColors.lightPurple),
            onPressed: () {
              _loadTodayMeals();
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(
                  content: Text('Refreshing...'),
                  backgroundColor: AppColors.lightPurple,
                ),
              );
            },
          ),
        ],
      ),
      body: SingleChildScrollView(
        child: Column(
          children: [
            _buildCalorieSummary(),
            _buildMacroSummary(),

            if (_showAIMeals) _buildAISection(),

            _buildMealSection('Breakfast', 'Breakfast', Icons.breakfast_dining),
            _buildMealSection('Lunch', 'Lunch', Icons.lunch_dining),
            _buildMealSection('Dinner', 'Dinner', Icons.dinner_dining),
            _buildMealSection('Snacks', 'Snack', Icons.local_cafe),

            // Complete Day Button
            Padding(
              padding: const EdgeInsets.all(16),
              child: ElevatedButton(
                onPressed: _completeDay,
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.green,
                  foregroundColor: Colors.white,
                  minimumSize: Size(double.infinity, 55),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                  ),
                  elevation: 3,
                ),
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(Icons.check_circle),
                    SizedBox(width: 10),
                    Text('Complete Today\'s Log', style: TextStyle(fontSize: 18)),
                  ],
                ),
              ),
            ),
            SizedBox(height: 20),
          ],
        ),
      ),
    );
  }
}
